services:
  app:
    build: .
    container_name: integra_app
    ports:
      - "${EXPRESSPORT}:3000"
    environment:
      HOST: postgres
      DATABASE: ${DATABASE}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      PORT: ${PORT}
      EXPRESSPORT: ${EXPRESSPORT}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
    command: ["npm", "start"]

  postgres:
    image: postgres:15
    container_name: integra_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
